const defaults=[{id:1,title:"Finaliser la proposition créative",role:"headliner",nature:"urgent",duration:"45 min",done:false,due:"",positive:"",negative:"",order:0},{id:2,title:"Répondre aux messages importants",role:"supporting",nature:"todo",duration:"15 min",done:false,due:"",positive:"",negative:"",order:1},{id:3,title:"Réserver le train pour Lyon",role:"supporting",nature:"desire",duration:"10 min",done:false,due:"",positive:"",negative:"",order:2},{id:4,title:"Classer les notes de la semaine",role:"extra",nature:"waiting",duration:"5 min",done:false,due:"",positive:"",negative:"",order:3}];
const $=id=>document.getElementById(id),localDateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`,today=()=>localDateKey(new Date()),weekKey=dateValue=>{const d=dateValue?new Date(`${dateValue}T12:00:00`):new Date(),m=new Date(d);m.setDate(d.getDate()-((d.getDay()+6)%7));return localDateKey(m)};
const roleNames={headliner:"Tête d’affiche",supporting:"Second rôle",extra:"Figuration"},natureNames={todo:"À faire",desire:"J’ai envie",urgent:"Urgent",waiting:"En attente"},decisionNames={today:"Aujourd’hui",reschedule:"Nouvelle date",split:"Découper",abandon:"Abandonner",delegate:"Déléguer"};
const normalizeAction=(a,t,i)=>typeof a==="string"?{id:`${t.id}-a-${i}`,title:a,done:false,due:"",durationMinutes:null,completedAt:"",status:"active",lastReviewed:""}:{id:a.id||`${t.id}-a-${i}`,title:a.title||"",done:!!a.done,due:a.due||"",durationMinutes:a.durationMinutes??null,completedAt:a.completedAt||"",status:a.status||"active",lastReviewed:a.lastReviewed||""};
const normalizeTask=(t,i)=>({...t,role:(t.dailyRank>0||t.role==="headliner")?"headliner":(t.role||"supporting"),nature:t.nature||"todo",actions:(Array.isArray(t.actions)?t.actions:[]).map((a,j)=>normalizeAction(a,t,j)),due:t.due||"",positive:t.positive||"",negative:t.negative||"",order:t.order!==undefined?t.order:i,lastReviewed:t.lastReviewed||"",outcome:t.outcome||"",scenario:t.scenario||"general",environment:t.environment||"pro",week:t.due?weekKey(t.due):(t.week||weekKey()),dailyRank:t.dailyRank!==undefined?t.dailyRank:(i<3?i+1:0),priorityOrder:t.priorityOrder??((t.dailyRank||t.role==="headliner")?i+1:null)});
let tasks=(JSON.parse(localStorage.getItem("procast-tasks")||"null")||defaults).map(normalizeTask);
let decisions=JSON.parse(localStorage.getItem("procast-decisions")||"[]"),scenarios=JSON.parse(localStorage.getItem("procast-scenarios")||'[{"id":"general","name":"Général","environment":"pro","emoji":"🎬"}]').map(s=>({...s,environment:s.environment||"pro",emoji:s.emoji||"🎬"})),episodes=JSON.parse(localStorage.getItem("procast-episodes")||"{}"),decors=JSON.parse(localStorage.getItem("procast-decors")||"[]"),motifs=JSON.parse(localStorage.getItem("procast-motifs")||"[]").map((m,i)=>({...m,history:Array.isArray(m.history)?m.history:[],days:Array.isArray(m.days)?m.days:[1,2,3,4,5],active:m.active!==false,order:m.order??i})),weeklyRituals=JSON.parse(localStorage.getItem("procast-weekly-rituals")||"[]"),pendingRituals=[],pendingConsolidation=null,reviewQueue=[],reviewIndex=0,scenarioFilter="all",scenarioViewAll=false,currentEnvironment=localStorage.getItem("procast-environment")||"pro",currentScenarioContext=null,dialogScrollY=0,editingActions=[],editingDecorItems=[],pendingDuration=null,pendingFinishSceneId=null,pendingQuickTaskId=null,currentDecorDetailId=null,appearanceMode=localStorage.getItem("procast-appearance")||"auto";
if(!scenarios.some(s=>s.environment==="personal"))scenarios.push({id:"personnel",name:"Personnel",environment:"personal",emoji:"🏠"});
const save=()=>{localStorage.setItem("procast-tasks",JSON.stringify(tasks));localStorage.setItem("procast-decisions",JSON.stringify(decisions));localStorage.setItem("procast-scenarios",JSON.stringify(scenarios));localStorage.setItem("procast-episodes",JSON.stringify(episodes));localStorage.setItem("procast-decors",JSON.stringify(decors));localStorage.setItem("procast-motifs",JSON.stringify(motifs));localStorage.setItem("procast-weekly-rituals",JSON.stringify(weeklyRituals));localStorage.setItem("procast-environment",currentEnvironment);localStorage.setItem("procast-appearance",appearanceMode)};
const escapeHtml=s=>(s||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const formatDue=v=>new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short"}).format(new Date(`${v}T12:00:00`));
function episodeInfo(start=weekKey()){const d=new Date(`${start}T12:00:00`),thursday=new Date(d);thursday.setDate(d.getDate()+3);const season=thursday.getFullYear(),firstThursday=new Date(season,0,4);firstThursday.setDate(firstThursday.getDate()+3-((firstThursday.getDay()+6)%7));const week=1+Math.round((thursday-firstThursday)/604800000);return {season,week,label:`Saison ${season} · Épisode semaine ${week}`}}
function natureBadge(t){return `<span class="nature-badge ${t.nature}">${natureNames[t.nature]}</span>`}
function spotlightIcon(){return `<svg class="spotlight-icon vintage-projector" viewBox="0 0 48 44" aria-hidden="true"><circle cx="14" cy="11" r="7"/><circle cx="30" cy="10" r="6"/><circle cx="14" cy="11" r="1.5"/><circle cx="30" cy="10" r="1.5"/><path d="M10 19h25v14H10zM35 22l11-6v18l-11-6M18 33l-6 9m17-9 6 9"/></svg>`}
function applyAppearance(){const dark=appearanceMode==="dark"||(appearanceMode==="auto"&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.dataset.theme=dark?"dark":"light";$('appearanceMode').value=appearanceMode;document.querySelector('meta[name="theme-color"]').content=dark?(currentEnvironment==="personal"?"#21191b":"#1b1a17"):(currentEnvironment==="personal"?"#f1e2e1":"#f5f0e7")}
function priorityCandidates(env=currentEnvironment){return tasks.filter(t=>!t.done&&t.environment===env&&(t.role==="headliner"||t.priorityOrder!=null)).sort((a,b)=>(Number(a.priorityOrder)||0)-(Number(b.priorityOrder)||0)||a.order-b.order)}
function movePriority(id,direction){const list=priorityCandidates(),index=list.findIndex(t=>t.id===id),target=list[index+direction];if(!target)return;[list[index].priorityOrder,target.priorityOrder]=[target.priorityOrder,list[index].priorityOrder];normalizePriorities();render()}
function reorderSceneFromGrip(id,offset,priorityOnly=false){const list=priorityOnly?priorityCandidates():tasks.filter(t=>!t.done&&t.environment===currentEnvironment&&t.week===weekKey()&&(scenarioFilter==="all"||t.scenario===scenarioFilter)).sort((a,b)=>a.order-b.order),index=list.findIndex(t=>t.id===id),targetIndex=Math.max(0,Math.min(list.length-1,index+offset));if(index<0||targetIndex===index)return;const moving=list[index],target=list[targetIndex];if(priorityOnly){const old=moving.priorityOrder;moving.priorityOrder=target.priorityOrder;target.priorityOrder=old;normalizePriorities()}else{const old=moving.order;moving.order=target.order;target.order=old}render();showToast("Ordre mis à jour.")}
function bindMotifReorder(){document.querySelectorAll("[data-motif-grip]").forEach(handle=>{let startY=0;handle.onpointerdown=e=>{startY=e.clientY;handle.setPointerCapture?.(e.pointerId)};handle.onpointerup=e=>{const list=motifs.filter(m=>m.environment===currentEnvironment).sort((a,b)=>a.order-b.order),index=list.findIndex(m=>m.id===handle.dataset.motifGrip),direction=e.clientY-startY>24?1:e.clientY-startY<-24?-1:0,target=list[index+direction];if(!direction||!target)return;[list[index].order,target.order]=[target.order,list[index].order];save();render()}})}
function openSceneQuick(id){const t=tasks.find(x=>x.id===id);if(!t)return;pendingQuickTaskId=id;$('sceneQuickTitle').textContent=t.title;$('sceneQuickDialog').showModal()}
function runSceneQuick(type){const t=tasks.find(x=>x.id===pendingQuickTaskId);if(!t)return;$('sceneQuickDialog').close();pendingQuickTaskId=null;if(type==="reschedule"){openEdit(t.id);$("taskDue").classList.add("visible");setTimeout(()=>$("taskDue").showPicker?.(),100);return}if(type==="split"){openEdit(t.id);addActionRow();return}decisions.push({type,...decisionSnapshot(t),date:new Date().toISOString(),taskId:t.id});t.done=true;t.dailyRank=0;t.priorityOrder=null;t.outcome=type;normalizePriorities();render();showToast(type==="delegate"?"Scène déléguée.":"Scène abandonnée.")}
function bindSceneGestures(){document.querySelectorAll('[data-scene-gesture]').forEach(card=>{let x=0,y=0;const grip=card.querySelector('.drag-grip'),id=Number(card.dataset.sceneGesture);if(grip){let gripY=0;grip.onpointerdown=e=>{e.stopPropagation();gripY=e.clientY;grip.setPointerCapture?.(e.pointerId);card.classList.add('is-reordering')};grip.onpointerup=e=>{e.stopPropagation();const dy=e.clientY-gripY,steps=Math.max(1,Math.round(Math.abs(dy)/62));card.classList.remove('is-reordering');if(Math.abs(dy)<24)return;reorderSceneFromGrip(id,dy<0?-steps:steps,card.classList.contains('priority-waiting'))};grip.onpointercancel=()=>card.classList.remove('is-reordering')}card.onpointerdown=e=>{if(e.target.closest('button')||e.target.closest('.drag-grip'))return;x=e.clientX;y=e.clientY;card.setPointerCapture?.(e.pointerId)};card.onpointerup=e=>{if(!x&&!y)return;const dx=e.clientX-x,dy=e.clientY-y;x=0;y=0;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy))dx<0?completeTask(id):openSceneQuick(id)}})}
const activeAction=a=>!a.done&&!["abandoned","delegated"].includes(a.status);
const dateFromKey=key=>new Date(`${key}T12:00:00`),shiftDate=(key,days)=>{const d=dateFromKey(key);d.setDate(d.getDate()+days);return localDateKey(d)},dateKeysBetween=(start,end)=>{const keys=[];for(let key=start;key<end;key=shiftDate(key,1))keys.push(key);return keys};
function motifScheduled(m,dateKey){if(!m.active||dateKey<(m.startDate||dateKey))return false;return (m.extraDates||[]).includes(dateKey)||m.frequency==="daily"||(m.days||[]).includes(dateFromKey(dateKey).getDay())}
function motifEntry(m,dateKey){return m.history.find(h=>h.date===dateKey)}
function motifMissedItems(){const earliest=shiftDate(today(),-30),items=[];motifs.filter(m=>m.environment===currentEnvironment&&m.active).forEach(m=>dateKeysBetween(m.startDate>earliest?m.startDate:earliest,today()).forEach(date=>{if(motifScheduled(m,date)&&!motifEntry(m,date))items.push({kind:"motif",motif:m,date})}));return items}
function reviewItems(){const sunday=new Date().getDay()===0,sceneItems=tasks.filter(t=>!t.done&&t.environment===currentEnvironment&&t.lastReviewed!==today()).filter(t=>t.due?t.due<today():sunday).map(t=>({task:t,action:null,kind:t.due?"late":"weekly"}));return [...sceneItems,...motifMissedItems()]}
function dueForReview(t){return reviewItems().some(item=>item.task?.id===t.id)}
function render(){
  const headline=tasks.find(t=>t.role==="headliner"&&!t.done);
  $("headlinerContent").innerHTML=headline?`<div class="headline-task"><button class="check" onclick="completeTask(${headline.id})">✓</button><div><h2>${escapeHtml(headline.title)}</h2><span class="meta">${escapeHtml(headline.duration||"À votre rythme")}${headline.due?` · ${formatDue(headline.due)}`:""}</span>${natureBadge(headline)}</div><button class="cast-button" onclick="openEdit(${headline.id})">Modifier</button></div>`:`<div class="empty-headliner">La scène est libre. Choisissez votre priorité du jour.</div>`;
  const active=tasks.filter(t=>!t.done&&t.id!==(headline?headline.id:null)).sort((a,b)=>a.order-b.order);
  $("taskList").innerHTML=active.map((t,i)=>`<div class="task-row"><button class="check" onclick="completeTask(${t.id})">✓</button><div class="task-copy"><span class="task-title">${escapeHtml(t.title)}</span>${natureBadge(t)}${t.due?`<span class="task-due ${t.due<=today()?"due-soon":""}">${formatDue(t.due)}</span>`:""}</div><span class="role-pill">${roleNames[t.role]}</span><span class="task-time">${escapeHtml(t.duration||"—")}</span><div class="row-actions"><button onclick="moveTask(${t.id},-1)" ${i===0?"disabled":""} aria-label="Monter">↑</button><button onclick="moveTask(${t.id},1)" ${i===active.length-1?"disabled":""} aria-label="Descendre">↓</button><button onclick="openEdit(${t.id})" aria-label="Modifier">•••</button></div></div>`).join("");
  $("taskCounter").textContent=`${active.length} rôle${active.length>1?"s":""} restant${active.length>1?"s":""}`;
  const done=tasks.filter(t=>t.done);$("doneCount").textContent=done.length;$("doneList").innerHTML=done.map(t=>`<div class="done-item"><span>${escapeHtml(t.title)}${t.outcome?` · ${decisionNames[t.outcome]||t.outcome}`:""}</span><button onclick="restoreTask(${t.id})">Restaurer</button></div>`).join("");
  const reviewable=tasks.filter(dueForReview);$("reviewCount").textContent=reviewable.length;$("reviewTrigger").disabled=reviewable.length===0;renderMobile();save();
}
function decisionSnapshot(t){return {nature:t.nature,environment:t.environment,scenario:t.scenario,role:t.role,actionsCount:t.actions.length,positive:t.positive||"",negative:t.negative||"",consequenceCategories:consequenceCategories(`${t.positive||""} ${t.negative||""}`)}}
function consequenceCategories(text){const value=text.toLocaleLowerCase("fr"),rules={finances:["coût","argent","budget","financ","économ"],relations:["quelqu’un","relation","patient","famille","équipe"],stress:["stress","charge mentale","calme","serein"],temps:["temps","retard","rapid","ensuite"],objectif:["objectif","avancer","projet","réuss"]};return Object.entries(rules).filter(([,words])=>words.some(word=>value.includes(word))).map(([category])=>category)}
function completeTask(id){const t=tasks.find(x=>x.id===id);if(!t||t.done)return;pendingDuration={type:"scene",taskId:id};$("durationEyebrow").textContent="SCÈNE TERMINÉE";$("durationActionTitle").textContent=t.title;$("durationDialog").showModal()}
function finalizeTask(id,minutes){const t=tasks.find(x=>x.id===id);t.done=true;t.outcome="completed";t.dailyRank=0;t.durationMinutes=minutes||null;t.completedAt=new Date().toISOString();decisions.push({type:"completed",minutes:t.durationMinutes,...decisionSnapshot(t),date:t.completedAt,taskId:t.id});normalizePriorities();render();showToast("Belle sortie de scène.")}
function restoreTask(id){const t=tasks.find(x=>x.id===id);t.done=false;t.outcome="";t.durationMinutes=null;t.completedAt="";render();showToast("De retour à l’affiche.")}
function toggleAction(taskId,actionId){const t=tasks.find(x=>x.id===taskId),a=t.actions.find(x=>String(x.id)===String(actionId));if(a.done){a.done=false;a.durationMinutes=null;a.completedAt="";render();return}pendingDuration={type:"action",taskId,actionId};$("durationEyebrow").textContent="ACTION TERMINÉE";$("durationActionTitle").textContent=a.title;$("durationDialog").showModal()}
function finishAction(minutes){if(!pendingDuration)return;const t=tasks.find(x=>x.id===pendingDuration.taskId),a=t.actions.find(x=>String(x.id)===String(pendingDuration.actionId));a.done=true;a.durationMinutes=minutes||null;a.completedAt=new Date().toISOString();a.lastReviewed=today();decisions.push({type:"action_completed",minutes:a.durationMinutes,nature:t.nature,environment:t.environment,date:a.completedAt,taskId:t.id,actionId:a.id});pendingDuration=null;$("durationDialog").close();render();if(t.actions.filter(x=>x.status==="active").length&&t.actions.filter(x=>x.status==="active").every(x=>x.done)){pendingFinishSceneId=t.id;$("finishSceneDialog").showModal()}}
function finishDuration(minutes){if(!pendingDuration)return;if(pendingDuration.type==="scene"){const id=pendingDuration.taskId;pendingDuration=null;$("durationDialog").close();finalizeTask(id,minutes);return}finishAction(minutes)}
function moveTask(id,dir){const a=tasks.filter(t=>!t.done&&t.environment===currentEnvironment&&t.role!=="headliner").sort((x,y)=>x.order-y.order),i=a.findIndex(t=>t.id===id),target=a[i+dir];if(i<0||!target)return;[a[i].order,target.order]=[target.order,a[i].order];render()}
function showToast(m){const el=$("toast");el.textContent=m;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function closeTaskDialog(){$("taskForm").reset();$("taskDialog").close();editingActions=[];if(document.activeElement)document.activeElement.blur();setTimeout(()=>window.scrollTo(0,dialogScrollY),120)}
function selectChip(id,value){$(id).value=value;document.querySelectorAll(`[data-choice="${id}"] [data-value]`).forEach(b=>b.classList.toggle("selected",b.dataset.value===value))}
function scenarioOptions(selected){const available=scenarios.filter(s=>s.environment===currentEnvironment),choice=selected||currentScenarioContext||(available[0]?.id||"");$("taskScenario").innerHTML=available.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join("");$("taskScenario").value=choice;$("scenarioChips").innerHTML=available.map(s=>`<button type="button" class="${s.id===choice?"selected":""}" data-scenario="${s.id}">${escapeHtml(s.emoji)} ${escapeHtml(s.name)}</button>`).join("");$("scenarioChips").querySelectorAll("button").forEach(b=>b.onclick=()=>{if(!currentScenarioContext)currentScenarioContext=b.dataset.scenario;$("taskScenario").value=b.dataset.scenario;$("scenarioChips").querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x===b))})}
function renderActionRows(){$("actionRows").innerHTML=editingActions.map((a,i)=>`<div class="action-edit-row"><button type="button" class="edit-grip" data-action-grip="${i}" aria-label="Faire glisser l’action">≡</button><input value="${escapeHtml(a.title)}" placeholder="Décrire l’action" data-action-title="${i}"><input type="date" value="${a.due||""}" data-action-due="${i}" aria-label="Échéance de l’action"><button type="button" data-remove-action="${i}" aria-label="Supprimer">×</button></div>`).join("");document.querySelectorAll("[data-action-title]").forEach(el=>{el.oninput=()=>editingActions[+el.dataset.actionTitle].title=el.value;el.onkeydown=event=>{if(event.key!=="Enter")return;event.preventDefault();editingActions[+el.dataset.actionTitle].title=el.value;const next=document.querySelector(`[data-action-title="${+el.dataset.actionTitle+1}"]`);if(next)next.focus();else addActionRow()}});document.querySelectorAll("[data-action-due]").forEach(el=>el.onchange=()=>editingActions[+el.dataset.actionDue].due=el.value);document.querySelectorAll("[data-remove-action]").forEach(el=>el.onclick=()=>{editingActions.splice(+el.dataset.removeAction,1);renderActionRows()});bindEditReorder("[data-action-grip]",editingActions,renderActionRows)}
function addActionRow(){editingActions.push({id:`action-${Date.now()}-${editingActions.length}`,title:"",done:false,due:"",durationMinutes:null,completedAt:"",status:"active",lastReviewed:""});renderActionRows();setTimeout(()=>$("actionRows").querySelector(".action-edit-row:last-child input")?.focus(),0)}
function syncDateChoice(){const value=$("taskDue").value,d=new Date(),dates=[];[0,1].forEach(offset=>{const copy=new Date(d);copy.setDate(copy.getDate()+offset);dates.push(localDateKey(copy))});const sunday=new Date(d);sunday.setDate(sunday.getDate()+(7-sunday.getDay())%7);document.querySelectorAll(".date-chips button").forEach(b=>b.classList.remove("selected"));let selected;if(value===dates[0])selected=document.querySelector('[data-date-offset="0"]');else if(value===dates[1])selected=document.querySelector('[data-date-offset="1"]');else if(value===localDateKey(sunday))selected=document.querySelector("[data-date-sunday]");else if(value)selected=$("customDateButton");if(selected)selected.classList.add("selected");$("taskDue").classList.toggle("visible",!!value&&selected===$("customDateButton"))}
function setTaskDate(value){$("taskDue").value=value;syncDateChoice()}
function openNew(){dialogScrollY=window.scrollY;$("taskDialog").dataset.environment=currentEnvironment;$("taskForm").reset();$("editingId").value="";scenarioOptions(currentScenarioContext);selectChip("taskRole","supporting");selectChip("taskNature","todo");editingActions=[];renderActionRows();syncDateChoice();$("dialogEyebrow").textContent="NOUVELLE SCÈNE";$("dialogTitle").textContent="Qu’est-ce qui mérite ton attention ?";$("saveTask").textContent="Créer";$("deleteTask").classList.remove("visible");$("taskDialog").showModal()}
function openEdit(id){dialogScrollY=window.scrollY;const t=tasks.find(x=>x.id===id);$("taskDialog").dataset.environment=t.environment;scenarioOptions(t.scenario);$("editingId").value=id;$("taskTitle").value=t.title;selectChip("taskRole",t.role);selectChip("taskNature",t.nature);editingActions=t.actions.map(a=>({...a}));renderActionRows();$("taskDue").value=t.due||"";syncDateChoice();$("taskPositive").value=t.positive||"";$("taskNegative").value=t.negative||"";$("dialogEyebrow").textContent="RÉÉCRIRE LA SCÈNE";$("dialogTitle").textContent="Ajuster la mise en scène";$("saveTask").textContent="Enregistrer";$("deleteTask").classList.add("visible");$("taskDialog").showModal()}
function openReview(){reviewQueue=reviewItems();reviewIndex=0;if(reviewQueue.length){renderReview();$("reviewDialog").showModal()}}
const reviewSuggestions={positive:["Moins de charge mentale","Gagner du temps ensuite","Avancer vers un objectif","Aider quelqu’un","Retrouver du calme"],negative:["Davantage de stress","Un retard","Un coût supplémentaire","Un impact sur quelqu’un","Rien de grave"]};
function reviewMeaningField(t,field,label){return `<div class="review-meaning ${field==="negative"?"negative":""}"><b>${label}</b><div class="review-suggestions">${reviewSuggestions[field].map(text=>`<button type="button" onclick="addReviewSuggestion('${field}','${text.replace(/'/g,"&#39;")}')">${text}</button>`).join("")}</div><textarea aria-label="${label}" oninput="updateReviewConsequence('${field}',this.value)" placeholder="À préciser…">${escapeHtml(t[field]||"")}</textarea></div>`}
function setDecisionCopy(values){document.querySelectorAll("[data-decision]").forEach(b=>{const copy=values[b.dataset.decision];b.style.display=copy?"":"none";if(copy)b.innerHTML=`<b>${copy[0]}</b><span>${copy[1]}</span>`})}
function renderReview(){const item=reviewQueue[reviewIndex];if(!item){$("reviewDialog").close();render();showToast("Le revisionnage est terminé.");return}$("reviewProgress").textContent=`${reviewIndex+1} sur ${reviewQueue.length}`;$("decisionDetail").innerHTML="";document.querySelectorAll("[data-decision]").forEach(b=>b.classList.remove("selected"));if(item.kind==="motif"){const m=item.motif;$("reviewProgress").textContent+=` · Motif du ${formatDue(item.date)}`;$("reviewTaskTitle").textContent=m.title;$("reviewConsequences").innerHTML=`<div class="consequence-item"><b>${motifStage(m).label}</b>${motifScore(m).done}/${motifScore(m).total||0} occurrences réalisées</div>`;setDecisionCopy({today:["Aujourd’hui","Je le fais aujourd’hui"],reschedule:["Modifier les jours","J’ajuste le rythme"],split:["Laisser passer","Cette occurrence est manquée"],abandon:["Mettre en pause","Je suspends le motif"],delegate:["Arrêter","Je termine ce motif"]});return}const t=item.task;$("reviewProgress").textContent+=` · ${item.kind==="weekly"?"Rendez-vous du dimanche":"En retard"}`;$("reviewTaskTitle").textContent=t.title;$("reviewConsequences").innerHTML=reviewMeaningField(t,"positive","Ce que cette scène rend possible")+reviewMeaningField(t,"negative","Si je la laisse de côté");setDecisionCopy({today:["Aujourd’hui","Je la garde à l’affiche"],reschedule:["Nouvelle date","Je la reprogramme consciemment"],split:["Découper","Je choisis une première petite scène"],abandon:["Abandonner","Je libère cette place"],delegate:["Déléguer","Je confie le rôle"]})}
function updateReviewConsequence(field,value){const item=reviewQueue[reviewIndex];if(item){item.task[field]=value;save()}}
function addReviewSuggestion(field,text){const item=reviewQueue[reviewIndex];if(!item)return;const current=item.task[field]||"";item.task[field]=current.includes(text)?current:[current,text].filter(Boolean).join(", ");save();renderReview()}
function recordDecision(type,extra={}){const item=reviewQueue[reviewIndex],t=item.task;decisions.push({type,...decisionSnapshot(t),date:new Date().toISOString(),taskId:t.id});Object.assign(t,{lastReviewed:today(),...extra});if(extra.due)t.week=weekKey(extra.due);reviewIndex++;renderReview()}
function recordMotifReview(type,extra={}){const item=reviewQueue[reviewIndex],m=item.motif;m.history.push({date:item.date,status:extra.status||"missed",reviewDecision:type,reviewedAt:new Date().toISOString()});if(extra.today)m.extraDates=[...new Set([...(m.extraDates||[]),today()])];decisions.push({type:`motif_${type}`,environment:m.environment,scenario:m.scenario,motifId:m.id,date:new Date().toISOString()});if(extra.active===false)m.active=false;if(extra.paused)m.active=false;reviewIndex++;save();renderReview()}
function adjustMotifFromReview(item){const m=item.motif;m.history.push({date:item.date,status:"missed",reviewDecision:"adjust",reviewedAt:new Date().toISOString()});decisions.push({type:"motif_adjust",environment:m.environment,scenario:m.scenario,motifId:m.id,date:new Date().toISOString()});save();$("reviewDialog").close();openMotif(m.id)}
function chooseDecision(type,button){document.querySelectorAll("[data-decision]").forEach(b=>b.classList.remove("selected"));button.classList.add("selected");const detail=$("decisionDetail"),item=reviewQueue[reviewIndex];if(item?.kind==="motif"){if(type==="today"){recordMotifReview(type,{status:"rescheduled",today:true});return}if(type==="split"){recordMotifReview("skip",{status:"missed"});return}if(type==="abandon"){recordMotifReview("pause",{status:"missed",paused:true});return}if(type==="delegate"){recordMotifReview("stop",{status:"missed",active:false});return}if(type==="reschedule"){adjustMotifFromReview(item);return}}if(type==="today")return recordDecision(type,{due:today()});if(type==="abandon")return recordDecision(type,{done:true,dailyRank:0,outcome:"abandon"});if(type==="delegate")return recordDecision(type,{done:true,dailyRank:0,outcome:"delegate"});if(type==="reschedule")detail.innerHTML=`<div class="detail-form"><input type="date" id="newDue" min="${today()}"><button onclick="confirmReschedule()">Fixer cette date</button></div>`;if(type==="split")detail.innerHTML=`<div class="detail-form"><input id="firstStep" placeholder="La plus petite première action"><button onclick="confirmSplit()">Créer l’action</button></div>`}
function confirmReschedule(){const due=$("newDue").value;if(due)recordDecision("reschedule",{due})}
function confirmSplit(){const title=$("firstStep").value.trim();if(!title)return;const item=reviewQueue[reviewIndex],t=item.task;t.actions.push(normalizeAction({title,due:today()},t,t.actions.length));recordDecision("split")}
function renderStats(){const types=["today","reschedule","split","abandon","delegate"],total=types.reduce((n,k)=>n+decisions.filter(d=>d.type===k).length,0),completed=decisions.filter(d=>d.type==="completed").length;$("statsSummary").innerHTML=`<div class="stat-card"><b>${completed}</b><span>Tâches terminées</span></div><div class="stat-card"><b>${total}</b><span>Choix observés</span></div><div class="stat-card"><b>${decisions.length?Math.round(completed/decisions.length*100):0}%</b><span>Sorties terminées</span></div>`;$("statsBars").innerHTML=types.map(type=>{const n=decisions.filter(d=>d.type===type).length,p=total?Math.round(n/total*100):0;return `<div class="bar-row"><span>${decisionNames[type]}</span><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><b>${n}</b></div>`}).join("");const top=types.map(type=>[type,decisions.filter(d=>d.type===type).length]).sort((a,b)=>b[1]-a[1])[0];$("statsNote").textContent=total?`Pour l’instant, ton réflexe le plus fréquent est « ${decisionNames[top[0]].toLowerCase()} ». Ce n’est pas un verdict : simplement une tendance à observer.`:"Tes tendances apparaîtront ici après quelques revues. L’objectif n’est pas la performance, mais la compréhension."}
function scenarioName(id){const scenario=scenarios.find(s=>s.id===id);return scenario?scenario.name:"Général"}
function scenarioEmoji(id){const scenario=scenarios.find(s=>s.id===id);return scenario?scenario.emoji:"🎬"}
function episodeKey(scenario,week){return `${scenario}|${week}`}
function episodeMeta(scenario,week){const key=episodeKey(scenario,week);if(!episodes[key])episodes[key]={objective:"",status:"filming"};return episodes[key]}
function updateEpisode(scenario,week,field,value){episodeMeta(scenario,week)[field]=value;save();renderMobile()}
function scenarioProgress(id){const list=tasks.filter(t=>t.week===weekKey()&&t.scenario===id),done=list.filter(t=>t.done).length;return {done,total:list.length,percent:list.length?Math.round(done/list.length*100):0}}
function motifScore(m){const history=m.history.filter(h=>["done","missed"].includes(h.status)).slice(-30),done=history.filter(h=>h.status==="done").length;return {done,total:30,observed:history.length,percent:Math.round(done/30*100)}}
function motifStage(m){const p=motifScore(m).percent;return p>=80?{label:"Scène culte",className:"cult"}:p>=60?{label:"En salle",className:"theater"}:p>=40?{label:"Montage",className:"editing"}:p>=20?{label:"Premières prises",className:"takes"}:{label:"En répétition",className:"rehearsal"}}
function motifDaysOfWeek(m){return m.frequency==="daily"?[0,1,2,3,4,5,6]:(m.days||[])}
function canActivateMotif(candidate,excludeId=""){const active=motifs.filter(m=>m.environment===candidate.environment&&m.active&&m.id!==excludeId);if(motifScore(candidate).done<6&&active.some(m=>motifScore(m).done<6))return {ok:false,reason:"Un autre Motif est encore en répétition."};const overloaded=motifDaysOfWeek(candidate).some(day=>active.filter(m=>motifDaysOfWeek(m).includes(day)).length>=3);if(overloaded)return {ok:false,reason:"Trois Motifs sont déjà prévus l’un de ces jours."};return {ok:true,reason:""}}
function motifDisplayStage(m){return m.waiting?"En attente":motifStage(m).label}
function completeMotif(id){const m=motifs.find(x=>x.id===id);if(!m)return;const entry=motifEntry(m,today());if(entry?.status==="done"){m.history=m.history.filter(h=>h!==entry);const decisionIndex=decisions.findLastIndex?.(d=>d.type==="motif_completed"&&d.motifId===m.id&&localDateKey(new Date(d.date))===today())??-1;if(decisionIndex>=0)decisions.splice(decisionIndex,1);save();render();showToast("Validation du motif annulée.");return}if(entry)return;m.history.push({date:today(),status:"done",completedAt:new Date().toISOString()});decisions.push({type:"motif_completed",environment:m.environment,scenario:m.scenario,motifId:m.id,date:new Date().toISOString()});const score=motifScore(m);save();render();showToast("Motif joué aujourd’hui.");if(score.percent>=80&&!m.consolidationAsked){m.consolidationAsked=true;pendingConsolidation=m.id;$("consolidationText").textContent=`${m.title} · ${score.done}/${score.total} occurrences réalisées`;$("consolidationDialog").showModal();save()}}
function renderDailyMotifs(){const list=motifs.filter(m=>m.environment===currentEnvironment&&motifScheduled(m,today())).sort((a,b)=>a.order-b.order);$("dailyMotifs").innerHTML=list.length?`<div class="daily-motifs-head"><span>MOTIFS DU JOUR</span><b>${list.filter(m=>motifEntry(m,today())?.status==="done").length}/${list.length}</b></div><div class="motif-today-list">${list.map(m=>{const score=motifScore(m),done=motifEntry(m,today())?.status==="done";return `<article class="motif-today ${done?"done":""}"><button onclick="completeMotif('${m.id}')" aria-label="${done?"Annuler la validation":"Valider le motif"}">${done?"✓":""}</button><div><b>${escapeHtml(m.title)}</b><small>${score.done}/${score.total}</small></div><button class="motif-more" onclick="openMotif('${m.id}')" aria-label="Ouvrir le motif">${m.active?"Ⅱ":"▶"}</button></article>`}).join("")}</div>`:""}
function scenarioSelectOptions(env,selected){return scenarios.filter(s=>s.environment===env).map(s=>`<option value="${s.id}" ${s.id===selected?"selected":""}>${escapeHtml(s.emoji)} ${escapeHtml(s.name)}</option>`).join("")}
function bindEditReorder(selector,list,rerender){document.querySelectorAll(selector).forEach(handle=>{let startY=0;handle.onpointerdown=e=>{startY=e.clientY;handle.setPointerCapture?.(e.pointerId)};handle.onpointerup=e=>{const index=Number(handle.dataset.actionGrip??handle.dataset.decorGrip),direction=e.clientY-startY>24?1:e.clientY-startY<-24?-1:0,target=index+direction;if(!direction||target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];rerender();setTimeout(()=>document.querySelector(`${selector.replace("]",`=\"${target}\"]`)}`)?.focus(),0)}})}
function renderDecorItemRows(){$("decorItemRows").innerHTML=editingDecorItems.map((item,i)=>`<div class="decor-item-row"><button type="button" class="edit-grip" data-decor-grip="${i}" aria-label="Faire glisser l’élément">≡</button><input value="${escapeHtml(item)}" placeholder="Décrire l’élément" data-decor-item="${i}"><button type="button" data-remove-decor-item="${i}" aria-label="Supprimer">×</button></div>`).join("");document.querySelectorAll("[data-decor-item]").forEach(input=>{input.oninput=()=>editingDecorItems[Number(input.dataset.decorItem)]=input.value;input.onkeydown=event=>{if(event.key!=="Enter")return;event.preventDefault();editingDecorItems[Number(input.dataset.decorItem)]=input.value;const next=document.querySelector(`[data-decor-item="${Number(input.dataset.decorItem)+1}"]`);if(next)next.focus();else addDecorItem()}});document.querySelectorAll("[data-remove-decor-item]").forEach(button=>button.onclick=()=>{editingDecorItems.splice(Number(button.dataset.removeDecorItem),1);renderDecorItemRows()});bindEditReorder("[data-decor-grip]",editingDecorItems,renderDecorItemRows)}
function addDecorItem(){editingDecorItems.push("");renderDecorItemRows();setTimeout(()=>$("decorItemRows").querySelector(".decor-item-row:last-child input")?.focus(),0)}
function openDecor(id){const d=decors.find(x=>x.id===id);$("decorForm").reset();$("editingDecorId").value=d?.id||"";$("decorEmoji").value=d?.emoji||"🎬";$("decorTitle").value=d?.title||"";$("decorScenario").innerHTML=scenarioSelectOptions(currentEnvironment,d?.scenario||currentScenarioContext);editingDecorItems=[...(d?.items||[])];renderDecorItemRows();$("saveDecor").textContent=d?"Enregistrer":"Créer";$("deleteDecor").classList.toggle("visible",!!d);$("decorDialog").showModal()}
function useDecor(id){const d=decors.find(x=>x.id===id);if(!d)return;currentScenarioContext=d.scenario;openNew();$("taskTitle").value=d.title;editingActions=d.items.map((title,i)=>normalizeAction({id:`action-${Date.now()}-${i}`,title}, {id:Date.now()},i));renderActionRows()}
function openDecorDetail(id){const d=decors.find(x=>x.id===id);if(!d)return;currentDecorDetailId=id;$("decorDetailTitle").textContent=`${d.emoji||"🎬"} ${d.title}`;$("decorDetailCount").textContent=`${d.items.length} élément${d.items.length>1?"s":""}`;$("decorDetailDialog").showModal()}
async function shareDecor(id){const d=decors.find(x=>x.id===id);if(!d)return;const payload={app:"Pro Cast Décor",version:1,exportedAt:new Date().toISOString(),decor:{title:d.title,emoji:d.emoji||"🎬",items:[...d.items]}},file=new File([JSON.stringify(payload,null,2)],`pro-cast-decor-${d.title.toLocaleLowerCase("fr").replace(/[^a-z0-9]+/g,"-")}.json`,{type:"application/json"});try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:d.title,text:"Un Décor Pro Cast à ajouter à tes checklists.",files:[file]});showToast("Décor partagé.");return}const url=URL.createObjectURL(file),link=document.createElement("a");link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast("Fichier de partage préparé.")}catch(error){if(error.name!=="AbortError")showToast("Le partage n’a pas pu s’ouvrir.")}}
function openMotif(id){const m=motifs.find(x=>x.id===id);$("motifForm").reset();$("editingMotifId").value=m?.id||"";$("motifTitle").value=m?.title||"";$("motifScenario").innerHTML=scenarioSelectOptions(currentEnvironment,m?.scenario||currentScenarioContext);$("motifFrequency").value=m?.frequency||"daily";$("motifStart").value=m?.startDate||today();document.querySelectorAll('#motifDays input').forEach(input=>input.checked=(m?.days||[1,2,3,4,5]).includes(Number(input.value)));$("motifDays").classList.toggle("visible",$("motifFrequency").value==="custom");$("saveMotif").textContent=m?"Enregistrer":"Créer";$("pauseMotif").classList.toggle("visible",!!m);$("pauseMotif").textContent=m?.active===false?"Réactiver le motif":"Mettre en pause";$("deleteMotif").classList.toggle("visible",!!m);$("motifDialog").showModal()}
function ritualDecisionCount(env,week,type){return decisions.filter(d=>(d.environment||"pro")===env&&d.type===type&&weekKey(localDateKey(new Date(d.date)))===week).length}
function ritualObservations(env,week){const weekDecisions=decisions.filter(d=>(d.environment||"pro")===env&&weekKey(localDateKey(new Date(d.date)))===week),counts={};weekDecisions.forEach(d=>counts[d.type]=(counts[d.type]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];return top?[`Le geste le plus fréquent a été « ${decisionNames[top[0]]||top[0].replaceAll("_"," ")} » (${top[1]} fois).`]:["Une semaine encore silencieuse : le journal commence à se construire."]}
function createWeeklyRitual(env,week){const info=episodeInfo(week),weekTasks=tasks.filter(t=>t.environment===env&&t.week===week),weekDecisionTotal=decisions.filter(d=>(d.environment||"pro")===env&&weekKey(localDateKey(new Date(d.date)))===week).length,completed=weekTasks.filter(t=>t.done&&t.outcome==="completed").length,abandoned=ritualDecisionCount(env,week,"abandon"),carried=weekTasks.filter(t=>!t.done),scenarioStats=scenarios.filter(s=>s.environment===env).map(s=>{const list=weekTasks.filter(t=>t.scenario===s.id),done=list.filter(t=>t.done).length;return {id:s.id,name:s.name,emoji:s.emoji,done,total:list.length,percent:list.length?Math.round(done/list.length*100):0}}),end=shiftDate(week,7),motifStats=motifs.filter(m=>m.environment===env).map(m=>{const planned=dateKeysBetween(week,end).filter(date=>motifScheduled(m,date)),done=planned.filter(date=>motifEntry(m,date)?.status==="done").length;return {id:m.id,title:m.title,done,planned:planned.length,stage:motifStage(m).label}}).filter(m=>m.planned);const ritual={id:`${env}-${week}`,environment:env,week,season:info.season,episode:info.week,createdAt:new Date().toISOString(),completed,carried:carried.length,abandoned,scenarioStats,motifStats,observations:ritualObservations(env,week),empty:weekTasks.length===0&&weekDecisionTotal===0&&motifStats.length===0};weeklyRituals.push(ritual);carried.forEach(t=>t.week=weekKey());return ritual}
function ensureWeeklyRituals(){const current=weekKey(),previous=shiftDate(current,-7);["pro","personal"].forEach(env=>{if(!weeklyRituals.some(r=>r.id===`${env}-${previous}`)){const ritual=createWeeklyRitual(env,previous);if(!ritual.empty)pendingRituals.push(ritual)}});save()}
function ritualHtml(r){return `<p class="ritual-clap">🎬</p><p class="eyebrow">${r.environment==="pro"?"PRO":"PERSO"} · SAISON ${r.season}</p><h2>Épisode ${r.episode}<br><i>terminé</i></h2><div class="ritual-numbers"><article><b>${r.completed}</b><span>Scènes réalisées</span></article><article><b>${r.carried}</b><span>Scènes reportées</span></article><article><b>${r.abandoned}</b><span>Scènes abandonnées</span></article></div><h3>Progression des scénarios</h3>${r.scenarioStats.map(s=>`<div class="ritual-progress"><span>${escapeHtml(s.emoji)} ${escapeHtml(s.name)}</span><b>${s.percent}%</b></div>`).join("")}<h3>Motifs de la semaine</h3>${r.motifStats.length?r.motifStats.map(m=>`<p class="ritual-note"><b>${escapeHtml(m.title)}</b> · ${m.done}/${m.planned} · ${m.stage}</p>`).join(""):`<p class="ritual-note">Aucun motif programmé.</p>`}<h3>Ce que la semaine raconte</h3>${r.observations.map(o=>`<p class="ritual-note">${escapeHtml(o)}</p>`).join("")}`}
function showNextRitual(){const ritual=pendingRituals.shift();if(!ritual)return;$("weeklyRitualContent").innerHTML=ritualHtml(ritual);$("weeklyRitualDialog").showModal()}
function openJournal(){$("journalList").innerHTML=weeklyRituals.filter(r=>r.environment===currentEnvironment&&!r.empty).sort((a,b)=>b.week.localeCompare(a.week)).map(r=>`<button class="journal-entry" onclick="openJournalEntry('${r.id}')"><span>🎬 Saison ${r.season}</span><b>Épisode ${r.episode}</b><small>${r.completed} réalisées · ${r.carried} reportées</small></button>`).join("")||`<div class="observation-empty">Le premier épisode apparaîtra ici après la fin de la semaine.</div>`;$("journalDialog").showModal()}
function openJournalEntry(id){const r=weeklyRituals.find(x=>x.id===id);$("journalDialog").close();$("weeklyRitualContent").innerHTML=ritualHtml(r);$("weeklyRitualDialog").showModal()}
function renderMobile(){
  $("mobileApp").classList.toggle("environment-personal",currentEnvironment==="personal");$("mobileApp").dataset.environment=currentEnvironment;document.querySelectorAll("[data-environment]").forEach(b=>b.classList.toggle("active",b.dataset.environment===currentEnvironment));applyAppearance();
  $("mobileDate").textContent=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
  normalizePriorities();const candidates=priorityCandidates(),priorities=candidates.slice(0,3),waitingPriorities=candidates.slice(3);
  const actionList=t=>t.actions.length?`<div class="scene-actions">${t.actions.filter(a=>a.status==="active").map(a=>`<button class="scene-action ${a.done?"done":""}" onclick="event.stopPropagation();toggleAction(${t.id},'${a.id}')"><span>${a.done?"✓":""}</span><b>${escapeHtml(a.title)}</b>${a.durationMinutes?`<small>${a.durationMinutes} min</small>`:""}</button>`).join("")}</div>`:"";
  $("priorityStack").innerHTML=[0,1,2].map(i=>{const t=priorities[i];return t?`<article class="priority-card"><span class="priority-number">TÊTE D’AFFICHE 0${i+1} · ${escapeHtml(scenarioName(t.scenario))}</span><button class="priority-check" onclick="completeTask(${t.id})">✓</button><h2>${escapeHtml(t.title)}</h2>${natureBadge(t)}${actionList(t)}<button class="priority-edit" onclick="openEdit(${t.id})">•••</button></article>`:`<div class="empty-priority">Tête d’affiche ${i+1} encore libre — choisis-la dans le Plan de tournage.</div>`}).join("");
  $("priorityQueueCount").textContent=waitingPriorities.length;$("priorityQueue").hidden=waitingPriorities.length===0;$("priorityQueueList").innerHTML=waitingPriorities.map(t=>`<article class="priority-waiting" data-scene-gesture="${t.id}"><span class="drag-grip" aria-hidden="true">⋮⋮</span><button onclick="openEdit(${t.id})"><b>${escapeHtml(t.title)}</b><small>${scenarioEmoji(t.scenario)} ${escapeHtml(scenarioName(t.scenario))}${t.due?` · ${formatDue(t.due)}`:""}</small></button><button class="priority-toggle selected" onclick="togglePriority(${t.id})" aria-label="Retirer des priorités">${spotlightIcon()}</button></article>`).join("");
  renderDailyMotifs();
  const reviewable=reviewItems();$("mobileReviewCount").textContent=reviewable.length;$("mobileReview").disabled=reviewable.length===0;$("revisionBadge").textContent=reviewable.length;$("revisionCard").disabled=reviewable.length===0;$("revisionCard").classList.toggle("visible",reviewable.length>0);$("revisionTitle").textContent=new Date().getDay()===0?"Revisionnage du dimanche":"Revisionnage";$("revisionSubtitle").textContent=reviewable.length?`${reviewable.length} scène${reviewable.length>1?"s":""} à revoir`:"Rien à revoir aujourd’hui";
  const environmentScenarios=scenarios.filter(s=>s.environment===currentEnvironment);$("scenarioFilters").innerHTML=`<button class="emoji-filter ${scenarioFilter==="all"?"active":""}" onclick="setScenarioFilter('all')" aria-label="Tous les scénarios" title="Tous">✦</button>`+environmentScenarios.map(s=>`<button class="emoji-filter ${scenarioFilter===s.id?"active":""}" onclick="setScenarioFilter('${s.id}')" aria-label="${escapeHtml(s.name)}" title="${escapeHtml(s.name)}">${escapeHtml(s.emoji)}</button>`).join("");
  const weekly=tasks.filter(t=>t.environment===currentEnvironment&&(scenarioViewAll?scenarioFilter!=="all"&&t.scenario===scenarioFilter:t.week===weekKey()&&!t.done&&(scenarioFilter==="all"||t.scenario===scenarioFilter))).sort((a,b)=>scenarioViewAll?b.week.localeCompare(a.week)||Number(a.done)-Number(b.done)||a.order-b.order:Number(a.done)-Number(b.done)||a.order-b.order);
  $("weekKicker").textContent=scenarioViewAll?`SCÉNARIO · ${scenarioName(scenarioFilter)}`:episodeInfo().label.toUpperCase();
  const taskCard=t=>`<article class="mobile-task ${t.done?"task-completed":""}" data-scene-gesture="${t.id}"><span class="drag-grip" aria-hidden="true">⋮⋮</span><button class="check" onclick="${t.done?`restoreTask(${t.id})`:`completeTask(${t.id})`}">${t.done?"✓":""}</button><div onclick="openEdit(${t.id})"><h3>${escapeHtml(t.title)}</h3><p>${scenarioEmoji(t.scenario)} ${escapeHtml(scenarioName(t.scenario))} · ${natureNames[t.nature]}${t.due?` · ${formatDue(t.due)}`:""}</p></div>${t.done?`<span class="completed-label">Terminé</span>`:`<button class="priority-toggle ${t.role==="headliner"?"selected":""}" onclick="togglePriority(${t.id})" aria-label="${t.role==="headliner"?"Retirer des priorités":"Mettre en priorité"}">${spotlightIcon()}</button>`}${actionList(t)}</article>`;
  if(!weekly.length)$("mobileWeekList").innerHTML=`<p class="empty-priority">Aucune scène dans cette sélection.</p>`;else if(scenarioViewAll){const groups=weekly.reduce((all,t)=>{if(!all[t.week])all[t.week]=[];all[t.week].push(t);return all},{});$("mobileWeekList").innerHTML=Object.entries(groups).map(([week,list])=>{const info=episodeInfo(week),done=list.filter(t=>t.done).length,percent=list.length?Math.round(done/list.length*100):0,meta=episodeMeta(scenarioFilter,week);return `<section class="episode-block"><div class="episode-heading"><div><span>SAISON ${info.season}</span><b>Épisode · Semaine ${info.week}</b></div><strong>${percent}%</strong></div><div class="episode-controls"><input value="${escapeHtml(meta.objective)}" placeholder="Objectif de l’épisode" onchange="updateEpisode('${scenarioFilter}','${week}','objective',this.value)"><select onchange="updateEpisode('${scenarioFilter}','${week}','status',this.value)"><option value="filming" ${meta.status==="filming"?"selected":""}>Tournage en cours</option><option value="finished" ${meta.status==="finished"?"selected":""}>Tournage terminé</option><option value="cut" ${meta.status==="cut"?"selected":""}>Coupé au montage</option></select></div>${list.map(taskCard).join("")}</section>`}).join("")}else $("mobileWeekList").innerHTML=weekly.map(taskCard).join("");
  bindSceneGestures();renderMobileStats();
}
function mostFrequent(entries,label){const ranked=Object.entries(entries).sort((a,b)=>b[1]-a[1]);return ranked.length?{key:ranked[0][0],count:ranked[0][1],label}:null}
function renderMobileStats(){
  const envDecisions=decisions.filter(d=>(d.environment||"pro")===currentEnvironment),choices=envDecisions.filter(d=>["today","reschedule","split","abandon","delegate"].includes(d.type)),completed=envDecisions.filter(d=>d.type==="completed"),actionEvents=envDecisions.filter(d=>d.type==="action_completed"),sceneMinutes=completed.reduce((sum,d)=>sum+(Number(d.minutes)||0),0),actionMinutes=actionEvents.reduce((sum,d)=>sum+(Number(d.minutes)||0),0),minutes=sceneMinutes||actionMinutes,envTasks=tasks.filter(t=>t.environment===currentEnvironment);
  const postponedByNature={},completedByNature={},blockedByScenario={};choices.filter(d=>d.type==="reschedule").forEach(d=>postponedByNature[d.nature]=(postponedByNature[d.nature]||0)+1);completed.forEach(d=>completedByNature[d.nature]=(completedByNature[d.nature]||0)+1);envTasks.filter(t=>!t.done&&t.due&&t.due<today()).forEach(t=>blockedByScenario[t.scenario]=(blockedByScenario[t.scenario]||0)+1);
  const postponed=mostFrequent(postponedByNature,"reporté"),easy=mostFrequent(completedByNature,"terminé"),blocked=mostFrequent(blockedByScenario,"bloqué"),splitChoices=choices.filter(d=>d.type==="split"),splitTaskIds=new Set(splitChoices.map(d=>d.taskId)),splitCompleted=completed.filter(d=>splitTaskIds.has(d.taskId)).length,financial=choices.filter(d=>(d.consequenceCategories||[]).includes("finances")),financialAbandoned=financial.filter(d=>d.type==="abandon").length;
  const hypotheses=[];if(splitChoices.length>=3)hypotheses.push({strong:splitCompleted?`${splitCompleted} scène${splitCompleted>1?"s":""} découpée${splitCompleted>1?"s":""} ensuite terminée${splitCompleted>1?"s":""}.`:"Le découpage n’a pas encore été suivi d’une scène terminée.",detail:`Hypothèse fondée sur ${splitChoices.length} décisions de découpage.`});if(financial.length>=3)hypotheses.push({strong:financialAbandoned===0?"Les scènes aux conséquences financières sont rarement abandonnées.":`${financialAbandoned} scène${financialAbandoned>1?"s":""} à conséquence financière abandonnée${financialAbandoned>1?"s":""}.`,detail:`Hypothèse fondée sur ${financial.length} revisionnages.`});
  const insightCards=[postponed&&`<article><span>LE PLUS REPORTÉ</span><b>${natureNames[postponed.key]||postponed.key}</b><small>${postponed.count} décision${postponed.count>1?"s":""}</small></article>`,easy&&`<article><span>TERMINÉ FACILEMENT</span><b>${natureNames[easy.key]||easy.key}</b><small>${easy.count} scène${easy.count>1?"s":""}</small></article>`,blocked&&`<article><span>LE PLUS BLOQUÉ</span><b>${scenarioEmoji(blocked.key)} ${escapeHtml(scenarioName(blocked.key))}</b><small>${blocked.count} scène${blocked.count>1?"s":""} en retard</small></article>`].filter(Boolean).join("");
  $("mobileStats").innerHTML=`<div class="observation-summary"><article><b>${completed.length}</b><span>Scènes terminées</span></article><article><b>${choices.length}</b><span>Revisionnages</span></article><article><b>${minutes?`${minutes} min`:"—"}</b><span>Temps observé</span></article></div><section class="observation-section"><p class="observation-label">CE QUE J’OBSERVE</p>${insightCards?`<div class="insight-grid">${insightCards}</div>`:`<div class="observation-empty">Les premières tendances apparaîtront après quelques scènes terminées et revisionnées.</div>`}</section><section class="observation-section"><p class="observation-label">MES RÉACTIONS</p><div class="stats-bars">${["today","reschedule","split","abandon","delegate"].map(type=>{const n=choices.filter(d=>d.type===type).length,p=choices.length?Math.round(n/choices.length*100):0;return `<div class="bar-row"><span>${decisionNames[type]}</span><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><b>${n}</b></div>`}).join("")}</div></section><section class="observation-section"><p class="observation-label">HYPOTHÈSES À CONFIRMER</p>${hypotheses.length?`<div class="hypothesis-list">${hypotheses.map(h=>`<article><b>${h.strong}</b><small>${h.detail}</small></article>`).join("")}</div>`:`<div class="observation-empty">Pas encore assez de données pour formuler une hypothèse fiable. Pro Cast observe sans conclure trop vite.</div>`}</section><section class="observation-section"><p class="observation-label">MES SCÉNARIOS · CETTE SEMAINE</p>${scenarios.filter(s=>s.environment===currentEnvironment).map(s=>{const p=scenarioProgress(s.id);return `<div class="scenario-progress"><div class="scenario-progress-head"><span>${escapeHtml(s.emoji)} ${escapeHtml(s.name)}</span><b>${p.percent}%</b></div><div class="scenario-track"><div class="scenario-fill" style="width:${p.percent}%"></div></div><small>${p.done} sur ${p.total} cette semaine</small></div>`}).join("")}</section>`
  const envMotifs=motifs.filter(m=>m.environment===currentEnvironment).sort((a,b)=>a.order-b.order),envDecors=decors.filter(d=>d.environment===currentEnvironment);$("mobileStats").innerHTML+=`<section class="observation-section"><div class="observation-section-head"><p class="observation-label">MES MOTIFS</p><small>1 en répétition · 3 maximum par jour</small></div>${envMotifs.length?`<div class="motif-observation-list">${envMotifs.map(m=>{const score=motifScore(m);return `<div class="motif-observation-row"><button class="motif-reorder" data-motif-grip="${m.id}" aria-label="Faire glisser le motif">≡</button><button onclick="openMotif('${m.id}')"><b>${escapeHtml(m.title)}</b><span>${motifDisplayStage(m)}</span><strong>${score.done}/${score.total}</strong><i style="width:${score.percent}%"></i></button></div>`}).join("")}</div>`:`<div class="observation-empty">Aucun motif pour le moment.</div>`}</section><section class="observation-section"><div class="observation-section-head"><p class="observation-label">MES DÉCORS</p><small>Le + crée un décor depuis les Coulisses.</small></div>${envDecors.length?`<div class="decor-list">${envDecors.map(d=>`<button class="decor-card" onclick="openDecorDetail('${d.id}')"><span>${escapeHtml(d.emoji||"🎬")}</span><div><b>${escapeHtml(d.title)}</b><small>${d.items.length} élément${d.items.length>1?"s":""}</small></div><strong>›</strong></button>`).join("")}</div>`:`<div class="observation-empty">Crée ici tes checklists réutilisables.</div>`}</section><button class="journal-button" onclick="openJournal()"><span>🎬</span><div><b>Journal des épisodes</b><small>Relire les rituels de fin de semaine</small></div><strong>›</strong></button><section class="coulisses-data"><p class="observation-label">MES DONNÉES</p><p>Conserve une copie de tes scènes, motifs, décors et rituels.</p><div><button onclick="exportData()">Sauvegarder</button><button onclick="$('importFile').click()">Restaurer</button></div></section>`
  bindMotifReorder();
}
function togglePriority(id){const t=tasks.find(x=>x.id===id);if(!t)return;if(t.role==="headliner"||t.priorityOrder!=null){t.role="supporting";t.priorityOrder=null;t.dailyRank=0;showToast("Retirée de l’affiche.")}else{t.role="headliner";t.priorityOrder=Math.max(0,...priorityCandidates(t.environment).map(x=>Number(x.priorityOrder)||0))+1;showToast(priorityCandidates(t.environment).length>3?"Ajoutée à Prochainement à l’affiche.":"La scène passe en Tête d’affiche.")}normalizePriorities();render()}
function normalizePriorities(){["pro","personal"].forEach(env=>priorityCandidates(env).forEach((t,i)=>{t.priorityOrder=i+1;t.dailyRank=i<3?i+1:0}))}
function showWeekPage(){document.querySelectorAll(".mobile-page").forEach(p=>p.classList.toggle("active",p.id==="weekPage"));document.querySelectorAll("[data-page]").forEach(n=>n.classList.toggle("active",n.dataset.page==="weekPage"))}
function setScenarioFilter(id){scenarioFilter=id;currentScenarioContext=id==="all"?null:id;scenarioViewAll=false;renderMobile()}
function openWeeklyScenario(id){scenarioFilter=id;currentScenarioContext=id;scenarioViewAll=false;$("scenarioDialog").close();showWeekPage();renderMobile()}
function openScenario(id){scenarioFilter=id;currentScenarioContext=id;scenarioViewAll=true;$("scenarioDialog").close();showWeekPage();renderMobile()}
function scenarioDrawerRow(s,globalView){const p=scenarioProgress(s.id),episode=episodeInfo();return `<div class="scenario-row-wrap"><button class="scenario-row scenario-link" onclick="${globalView?"openScenario":"openWeeklyScenario"}('${s.id}')"><div class="scenario-row-head"><div><b>${escapeHtml(s.emoji)} ${escapeHtml(s.name)}</b><small>${episode.label}</small></div><span>${p.percent}% · ${p.done}/${p.total} ›</span></div><div class="scenario-track"><div class="scenario-fill" style="width:${p.percent}%"></div></div></button><button class="scenario-edit" onclick="editScenario('${s.id}')" aria-label="Modifier ${escapeHtml(s.name)}">✎</button></div>`}
function openScenarios(){const available=scenarios.filter(s=>s.environment===currentEnvironment),weeklyIds=new Set(tasks.filter(t=>t.environment===currentEnvironment&&t.week===weekKey()).map(t=>t.scenario));$("weeklyScenarioList").innerHTML=available.filter(s=>weeklyIds.has(s.id)).map(s=>scenarioDrawerRow(s,false)).join("")||`<p class="drawer-empty">Aucun scénario cette semaine.</p>`;$("scenarioList").innerHTML=available.map(s=>scenarioDrawerRow(s,true)).join("");const availableDecors=decors.filter(d=>d.environment===currentEnvironment);$("drawerDecorList").innerHTML=availableDecors.map(d=>`<button class="drawer-decor drawer-decor-link" onclick="$('scenarioDialog').close();openDecorDetail('${d.id}')"><span>${escapeHtml(d.emoji||"🎬")}</span><div><b>${escapeHtml(d.title)}</b><small>${d.items.length} élément${d.items.length>1?"s":""}</small></div><strong>›</strong></button>`).join("")||`<p class="drawer-empty">Aucun décor pour le moment.</p>`;cancelScenarioEdit();$("taskSearch").value="";$("searchResults").innerHTML="";$("appearanceMode").value=appearanceMode;$("scenarioDialog").showModal()}
function useDecorFromDrawer(id){$("scenarioDialog").close();useDecor(id)}
function editDecorFromDrawer(id){$("scenarioDialog").close();openDecor(id)}
function searchTasks(query){const q=query.trim().toLocaleLowerCase("fr");if(!q){$("searchResults").innerHTML="";return}const found=tasks.filter(t=>t.environment===currentEnvironment&&[t.title,(t.actions||[]).map(a=>a.title).join(" "),scenarioName(t.scenario),episodeInfo(t.week).label].join(" ").toLocaleLowerCase("fr").includes(q)).slice(0,20);$("searchResults").innerHTML=found.length?found.map(t=>`<button onclick="openSearchResult(${t.id})"><b>${escapeHtml(t.title)}</b><span>${scenarioEmoji(t.scenario)} ${escapeHtml(scenarioName(t.scenario))} · semaine ${episodeInfo(t.week).week}</span></button>`).join(""):`<p class="drawer-empty">Aucune scène trouvée.</p>`}
const emojiChoices=["🎬","💼","🩺","🔬","📚","🏠","💶","🌿","❤️","🧠","✨","🎯","🗂️","✈️","🍎","🧘"];
function renderEmojiPalette(){const render=(container,input)=>{$(container).innerHTML=emojiChoices.map(e=>`<button type="button">${e}</button>`).join("");$(container).querySelectorAll("button").forEach(b=>b.onclick=()=>{$(input).value=b.textContent})};render("emojiPalette","scenarioEmoji");render("planEmojiPalette","planScenarioEmoji")}
function editScenario(id){const s=scenarios.find(x=>x.id===id);$("editingScenarioId").value=id;$("scenarioName").value=s.name;$("scenarioEmoji").value=s.emoji;$("saveScenario").textContent="Enregistrer";$("scenarioForm").classList.add("editing");$("cancelScenarioEdit").classList.add("visible");$("scenarioName").focus()}
function cancelScenarioEdit(){$("scenarioForm").reset();$("editingScenarioId").value="";$("saveScenario").textContent="Enregistrer";$("scenarioForm").classList.remove("editing");$("cancelScenarioEdit").classList.remove("visible")}
function openSearchResult(id){$("scenarioDialog").close();openEdit(id)}
function switchEnvironment(env){currentEnvironment=env;scenarioFilter="all";currentScenarioContext=null;scenarioViewAll=false;render()}
function handleContextAdd(){const page=document.querySelector(".mobile-page.active")?.id;if(page==="observePage")openDecor();else if(page==="weekPage")$("addChoiceDialog").showModal();else openNew()}
function exportData(){const backup={app:"Pro Cast",version:11,exportedAt:new Date().toISOString(),tasks,decisions,scenarios,episodes,decors,motifs,weeklyRituals};const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`pro-cast-sauvegarde-${today()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast("Sauvegarde préparée.")}
async function importData(file){try{const backup=JSON.parse(await file.text());if(backup.app==="Pro Cast Décor"&&backup.decor?.title&&Array.isArray(backup.decor.items)){decors.push({id:`decor-${Date.now()}`,title:backup.decor.title,emoji:backup.decor.emoji||"🎬",items:backup.decor.items.map(String),scenario:currentScenarioContext||scenarios.find(s=>s.environment===currentEnvironment)?.id||"general",environment:currentEnvironment});save();renderMobileStats();showToast("Décor ajouté à tes Coulisses.");return}if(backup.app!=="Pro Cast"||!Array.isArray(backup.tasks)||!Array.isArray(backup.scenarios))throw new Error("format");if(!confirm(`Restaurer ${backup.tasks.length} scènes ? Les données actuelles seront remplacées.`))return;localStorage.setItem("procast-before-import",JSON.stringify({tasks,decisions,scenarios,episodes,decors,motifs,weeklyRituals,date:new Date().toISOString()}));tasks=backup.tasks.map(normalizeTask);decisions=Array.isArray(backup.decisions)?backup.decisions:[];scenarios=backup.scenarios;episodes=backup.episodes||{};decors=backup.decors||[];motifs=(backup.motifs||[]).map((m,i)=>({...m,order:m.order??i}));weeklyRituals=backup.weeklyRituals||[];scenarioFilter="all";currentScenarioContext=null;scenarioViewAll=false;save();$("scenarioDialog").close();render();showToast("Sauvegarde restaurée.")}catch(error){showToast("Ce fichier n’est pas une sauvegarde Pro Cast.")}finally{$("importFile").value=""}}
$("dateLabel").textContent=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());$("addTrigger").onclick=openNew;$("mobileAdd").onclick=handleContextAdd;$("cancelTask").onclick=closeTaskDialog;$("doneToggle").onclick=()=>$("doneList").classList.toggle("open");$("reviewTrigger").onclick=openReview;$("mobileReview").onclick=openReview;$("revisionCard").onclick=openReview;$("closeReview").onclick=()=>$("reviewDialog").close();$("statsTrigger").onclick=()=>{renderStats();$("statsDialog").showModal()};$("closeStats").onclick=()=>$("statsDialog").close();$("scenarioTrigger").onclick=openScenarios;$("closeScenarios").onclick=()=>$("scenarioDialog").close();document.querySelectorAll("[data-decision]").forEach(b=>b.onclick=()=>chooseDecision(b.dataset.decision,b));document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mobile-page").forEach(p=>p.classList.toggle("active",p.id===b.dataset.page));document.querySelectorAll("[data-page]").forEach(n=>n.classList.toggle("active",n===b));if(b.dataset.page==="observePage")renderMobileStats()});
$("scenarioForm").addEventListener("submit",e=>{e.preventDefault();const name=$("scenarioName").value.trim(),id=$("editingScenarioId").value;if(!name||!id)return;Object.assign(scenarios.find(s=>s.id===id),{name,emoji:$("scenarioEmoji").value.trim()||"🎬",environment:currentEnvironment});cancelScenarioEdit();openScenarios();render();showToast("Scénario mis à jour.")});$("cancelScenarioEdit").onclick=cancelScenarioEdit;renderEmojiPalette();
$("taskSearch").addEventListener("input",e=>searchTasks(e.target.value));
document.querySelectorAll("[data-environment]").forEach(b=>b.onclick=()=>switchEnvironment(b.dataset.environment));
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"})));
$("importFile").onchange=e=>{if(e.target.files[0])importData(e.target.files[0])};
$("createSceneChoice").onclick=()=>{$("addChoiceDialog").close();openNew()};$("createMotifChoice").onclick=()=>{$("addChoiceDialog").close();openMotif()};$("createScenarioChoice").onclick=()=>{$("addChoiceDialog").close();$("planScenarioForm").reset();$("planScenarioEmoji").value="🎬";$("planScenarioDialog").showModal()};$("cancelAddChoice").onclick=()=>$("addChoiceDialog").close();$("cancelPlanScenario").onclick=()=>$("planScenarioDialog").close();$("planScenarioForm").addEventListener("submit",e=>{e.preventDefault();const name=$("planScenarioName").value.trim();if(!name)return;const scenario={id:`scenario-${Date.now()}`,name,emoji:$("planScenarioEmoji").value.trim()||"🎬",environment:currentEnvironment};scenarios.push(scenario);currentScenarioContext=scenario.id;scenarioFilter=scenario.id;$("planScenarioDialog").close();save();render();showToast("Nouveau scénario au Plan de tournage.")});
$("addDecorItem").onclick=addDecorItem;$("cancelDecor").onclick=()=>$("decorDialog").close();$("decorForm").addEventListener("submit",e=>{e.preventDefault();const id=$("editingDecorId").value,title=$("decorTitle").value.trim(),values={title,emoji:$("decorEmoji").value.trim()||"🎬",scenario:$("decorScenario").value,environment:currentEnvironment,items:editingDecorItems.map(x=>x.trim()).filter(Boolean)};if(id)Object.assign(decors.find(d=>d.id===id),values);else decors.push({id:`decor-${Date.now()}`,...values});editingDecorItems=[];$("decorDialog").close();save();renderMobileStats();showToast(id?"Décor modifié.":"Décor installé dans les Coulisses.")});$("deleteDecor").onclick=()=>{const id=$("editingDecorId").value;decors=decors.filter(d=>d.id!==id);editingDecorItems=[];$("decorDialog").close();save();renderMobileStats();showToast("Décor retiré.")};
$("closeDecorDetail").onclick=()=>$("decorDetailDialog").close();$("useDecorDetail").onclick=()=>{$("decorDetailDialog").close();useDecor(currentDecorDetailId)};$("editDecorDetail").onclick=()=>{$("decorDetailDialog").close();openDecor(currentDecorDetailId)};$("shareDecorDetail").onclick=()=>shareDecor(currentDecorDetailId);
$("cancelSceneQuick").onclick=()=>{$("sceneQuickDialog").close();pendingQuickTaskId=null};document.querySelectorAll("[data-quick]").forEach(button=>button.onclick=()=>runSceneQuick(button.dataset.quick));
$("appearanceMode").onchange=e=>{appearanceMode=e.target.value;applyAppearance();save()};matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change",()=>{if(appearanceMode==="auto")applyAppearance()});
$("motifFrequency").onchange=()=>$("motifDays").classList.toggle("visible",$("motifFrequency").value==="custom");$("cancelMotif").onclick=()=>$("motifDialog").close();$("motifForm").addEventListener("submit",e=>{e.preventDefault();const id=$("editingMotifId").value,frequency=$("motifFrequency").value,days=frequency==="daily"?[0,1,2,3,4,5,6]:[...document.querySelectorAll('#motifDays input:checked')].map(x=>Number(x.value)),values={title:$("motifTitle").value.trim(),scenario:$("motifScenario").value,environment:currentEnvironment,frequency,days,startDate:$("motifStart").value||today()};let message;if(id){const m=motifs.find(x=>x.id===id);Object.assign(m,values);if(m.active){const check=canActivateMotif(m,id);if(!check.ok){m.active=false;m.waiting=true;message=`${check.reason} Motif placé en attente.`}}}else{const candidate={id:`motif-${Date.now()}`,...values,active:true,waiting:false,history:[],createdAt:new Date().toISOString(),consolidationAsked:false},check=canActivateMotif(candidate);if(!check.ok){candidate.active=false;candidate.waiting=true;message=`${check.reason} Motif placé en attente.`}motifs.push(candidate)}$("motifDialog").close();save();render();showToast(message||(id?"Motif ajusté.":"Le motif entre en répétition."))});$("pauseMotif").onclick=()=>{const m=motifs.find(x=>x.id===$("editingMotifId").value);if(m.active){m.active=false;m.waiting=false;$("motifDialog").close();save();render();showToast("Motif mis en pause.");return}const check=canActivateMotif(m,m.id);if(!check.ok){m.waiting=true;$("motifDialog").close();save();render();showToast(`${check.reason} Il reste en attente.`);return}m.active=true;m.waiting=false;$("motifDialog").close();save();render();showToast("Motif réactivé.")};$("deleteMotif").onclick=()=>{motifs=motifs.filter(m=>m.id!==$("editingMotifId").value);$("motifDialog").close();save();render();showToast("Motif retiré.")};
document.querySelectorAll("[data-consolidation]").forEach(b=>b.onclick=()=>{const m=motifs.find(x=>x.id===pendingConsolidation),choice=b.dataset.consolidation;if(!m)return;if(choice==="stop")m.active=false;if(choice==="space"){$("consolidationDialog").close();openMotif(m.id);pendingConsolidation=null;return}m.consolidationChoice=choice;pendingConsolidation=null;$("consolidationDialog").close();save();render()});
$("closeWeeklyRitual").onclick=()=>{$("weeklyRitualDialog").close();setTimeout(showNextRitual,180)};$("closeJournal").onclick=()=>$("journalDialog").close();
document.querySelectorAll(".choice-chips").forEach(group=>group.querySelectorAll("[data-value]").forEach(b=>b.onclick=()=>selectChip(group.dataset.choice,b.dataset.value)));$("addAction").onclick=addActionRow;document.querySelectorAll("[data-date-offset]").forEach(b=>b.onclick=()=>{const d=new Date();d.setDate(d.getDate()+Number(b.dataset.dateOffset));setTaskDate(localDateKey(d))});document.querySelector("[data-date-sunday]").onclick=()=>{const d=new Date(),delta=(7-d.getDay())%7;d.setDate(d.getDate()+delta);setTaskDate(localDateKey(d))};$("customDateButton").onclick=()=>{$("taskDue").classList.add("visible");$("taskDue").showPicker?.()};$("taskDue").onchange=syncDateChoice;document.querySelectorAll(".suggestion-chips").forEach(group=>group.querySelectorAll("button").forEach(b=>b.onclick=()=>{const field=$(group.dataset.target),text=b.textContent;field.value=field.value.includes(text)?field.value.replace(text,"").replace(/^, |, $/g,"").replace(", , ",", "):field.value+(field.value?", ":"")+text;b.classList.toggle("selected")}));
document.querySelectorAll("[data-minutes]").forEach(b=>b.onclick=()=>finishDuration(Number(b.dataset.minutes)));$("cancelDuration").onclick=()=>{pendingDuration=null;$("durationDialog").close()};$("confirmFinishScene").onclick=()=>{const id=pendingFinishSceneId;pendingFinishSceneId=null;$("finishSceneDialog").close();completeTask(id)};$("keepSceneOpen").onclick=()=>{pendingFinishSceneId=null;$("finishSceneDialog").close()};
$("taskForm").addEventListener("submit",e=>{e.preventDefault();const title=$("taskTitle").value.trim();if(!title)return;const role=$("taskRole").value,id=Number($("editingId").value),due=$("taskDue").value,formEnvironment=$("taskDialog").dataset.environment||currentEnvironment,existing=id?tasks.find(t=>t.id===id):null;const priorityOrder=role==="headliner"?(existing?.priorityOrder??Math.max(0,...priorityCandidates(formEnvironment).map(x=>Number(x.priorityOrder)||0))+1):null,values={title,role,nature:$("taskNature").value,actions:editingActions.filter(a=>a.title.trim()).map(a=>({...a,title:a.title.trim()})),scenario:$("taskScenario").value,environment:formEnvironment,duration:"",due,week:weekKey(due),positive:$("taskPositive").value.trim(),negative:$("taskNegative").value.trim(),lastReviewed:"",priorityOrder};if(id)Object.assign(existing,values);else tasks.push({id:Date.now(),...values,done:false,order:tasks.length,outcome:"",dailyRank:0});currentEnvironment=formEnvironment;currentScenarioContext=values.scenario;normalizePriorities();closeTaskDialog();render();showToast(id?"La scène a été réécrite.":role==="headliner"&&priorityCandidates(formEnvironment).length>3?"La scène rejoint Prochainement à l’affiche.":"La scène entre en tournage.")});$("deleteTask").onclick=()=>{const id=Number($("editingId").value);tasks=tasks.filter(t=>t.id!==id);normalizePriorities();closeTaskDialog();render();showToast("Coupée au montage.")};$("resetDay").onclick=()=>{tasks=structuredClone(defaults).map((t,i)=>normalizeTask({...t,actions:[],scenario:"general",environment:"pro",week:weekKey(),dailyRank:i<3?i+1:0},i));decisions=[];episodes={};render();showToast("La scène est prête.")};if("serviceWorker" in navigator&&location.protocol.startsWith("http"))window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));ensureWeeklyRituals();applyAppearance();render();setTimeout(showNextRitual,350);
