const defaults=[{id:1,title:"Finaliser la proposition créative",role:"headliner",nature:"urgent",duration:"45 min",done:false,due:"",positive:"",negative:"",order:0},{id:2,title:"Répondre aux messages importants",role:"supporting",nature:"todo",duration:"15 min",done:false,due:"",positive:"",negative:"",order:1},{id:3,title:"Réserver le train pour Lyon",role:"supporting",nature:"desire",duration:"10 min",done:false,due:"",positive:"",negative:"",order:2},{id:4,title:"Classer les notes de la semaine",role:"extra",nature:"waiting",duration:"5 min",done:false,due:"",positive:"",negative:"",order:3}];
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),weekKey=dateValue=>{const d=dateValue?new Date(`${dateValue}T12:00:00`):new Date(),m=new Date(d);m.setDate(d.getDate()-((d.getDay()+6)%7));return m.toISOString().slice(0,10)};
const roleNames={headliner:"Tête d’affiche",supporting:"Second rôle",extra:"Figuration"},natureNames={todo:"À faire",desire:"J’ai envie",urgent:"Urgent",waiting:"En attente"},decisionNames={today:"Aujourd’hui",reschedule:"Nouvelle date",split:"Découper",abandon:"Abandonner",delegate:"Déléguer"};
let tasks=(JSON.parse(localStorage.getItem("procast-tasks")||"null")||defaults).map((t,i)=>({...t,nature:t.nature||"todo",due:t.due||"",positive:t.positive||"",negative:t.negative||"",order:t.order!==undefined?t.order:i,lastReviewed:t.lastReviewed||"",outcome:t.outcome||"",scenario:t.scenario||"general",environment:t.environment||"pro",week:t.due?weekKey(t.due):(t.week||weekKey()),dailyRank:t.dailyRank!==undefined?t.dailyRank:(i<3?i+1:0)}));
let decisions=JSON.parse(localStorage.getItem("procast-decisions")||"[]"),scenarios=JSON.parse(localStorage.getItem("procast-scenarios")||'[{"id":"general","name":"Général","environment":"pro"}]').map(s=>({...s,environment:s.environment||"pro"})),reviewQueue=[],reviewIndex=0,scenarioFilter="all",scenarioViewAll=false,currentEnvironment=localStorage.getItem("procast-environment")||"pro";
if(!scenarios.some(s=>s.environment==="personal"))scenarios.push({id:"personnel",name:"Personnel",environment:"personal"});
const save=()=>{localStorage.setItem("procast-tasks",JSON.stringify(tasks));localStorage.setItem("procast-decisions",JSON.stringify(decisions));localStorage.setItem("procast-scenarios",JSON.stringify(scenarios));localStorage.setItem("procast-environment",currentEnvironment)};
const escapeHtml=s=>(s||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const formatDue=v=>new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short"}).format(new Date(`${v}T12:00:00`));
function episodeInfo(start=weekKey()){const d=new Date(`${start}T12:00:00`),thursday=new Date(d);thursday.setDate(d.getDate()+3);const season=thursday.getFullYear(),firstThursday=new Date(season,0,4);firstThursday.setDate(firstThursday.getDate()+3-((firstThursday.getDay()+6)%7));const week=1+Math.round((thursday-firstThursday)/604800000);return {season,week,label:`Saison ${season} · Épisode semaine ${week}`}}
function natureBadge(t){return `<span class="nature-badge ${t.nature}">${natureNames[t.nature]}</span>`}
function spotlightIcon(){return `<svg class="spotlight-icon" viewBox="0 0 48 44" aria-hidden="true"><path class="spotlight-beam" d="M17 11 1 3v30l16-11z"/><path class="spotlight-lens" d="M16 10h4v13h-4z"/><path class="spotlight-body" d="M20 9h12c5 0 9 3 9 7s-4 7-9 7H20z"/><path class="spotlight-cap" d="M40 13h5v6h-5"/><path class="spotlight-yoke" d="M23 24v4h11v-6"/><path class="spotlight-stand" d="M28.5 28v5m0 0-8 9m8-9 8 9"/><path class="spotlight-rays" d="m11 6-4-4M10 17H4m8 9-4 4"/></svg>`}
function dueForReview(t){return !t.done&&t.due&&t.due<=today()&&t.lastReviewed!==today()}
function render(){
  const headline=tasks.find(t=>t.role==="headliner"&&!t.done);
  $("headlinerContent").innerHTML=headline?`<div class="headline-task"><button class="check" onclick="completeTask(${headline.id})">✓</button><div><h2>${escapeHtml(headline.title)}</h2><span class="meta">${escapeHtml(headline.duration||"À votre rythme")}${headline.due?` · ${formatDue(headline.due)}`:""}</span>${natureBadge(headline)}</div><button class="cast-button" onclick="openEdit(${headline.id})">Modifier</button></div>`:`<div class="empty-headliner">La scène est libre. Choisissez votre priorité du jour.</div>`;
  const active=tasks.filter(t=>!t.done&&t.id!==(headline?headline.id:null)).sort((a,b)=>a.order-b.order);
  $("taskList").innerHTML=active.map((t,i)=>`<div class="task-row"><button class="check" onclick="completeTask(${t.id})">✓</button><div class="task-copy"><span class="task-title">${escapeHtml(t.title)}</span>${natureBadge(t)}${t.due?`<span class="task-due ${t.due<=today()?"due-soon":""}">${formatDue(t.due)}</span>`:""}</div><span class="role-pill">${roleNames[t.role]}</span><span class="task-time">${escapeHtml(t.duration||"—")}</span><div class="row-actions"><button onclick="moveTask(${t.id},-1)" ${i===0?"disabled":""} aria-label="Monter">↑</button><button onclick="moveTask(${t.id},1)" ${i===active.length-1?"disabled":""} aria-label="Descendre">↓</button><button onclick="openEdit(${t.id})" aria-label="Modifier">•••</button></div></div>`).join("");
  $("taskCounter").textContent=`${active.length} rôle${active.length>1?"s":""} restant${active.length>1?"s":""}`;
  const done=tasks.filter(t=>t.done);$("doneCount").textContent=done.length;$("doneList").innerHTML=done.map(t=>`<div class="done-item"><span>${escapeHtml(t.title)}${t.outcome?` · ${decisionNames[t.outcome]||t.outcome}`:""}</span><button onclick="restoreTask(${t.id})">Restaurer</button></div>`).join("");
  const reviewable=tasks.filter(dueForReview);$("reviewCount").textContent=reviewable.length;$("reviewTrigger").disabled=reviewable.length===0;renderMobile();save();
}
function completeTask(id){const t=tasks.find(x=>x.id===id);t.done=true;t.outcome="completed";t.dailyRank=0;decisions.push({type:"completed",nature:t.nature,environment:t.environment,date:new Date().toISOString()});normalizePriorities();render();showToast("Belle sortie de scène.")}
function restoreTask(id){const t=tasks.find(x=>x.id===id);t.done=false;t.outcome="";render();showToast("De retour à l’affiche.")}
function moveTask(id,dir){const a=tasks.filter(t=>!t.done&&t.role!=="headliner").sort((x,y)=>x.order-y.order),i=a.findIndex(t=>t.id===id),target=a[i+dir];if(!target)return;[a[i].order,target.order]=[target.order,a[i].order];render()}
function showToast(m){const el=$("toast");el.textContent=m;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function closeTaskDialog(){$("taskForm").reset();$("taskDialog").close()}
function scenarioOptions(selected){const available=scenarios.filter(s=>s.environment===currentEnvironment),choice=selected||(available[0]?available[0].id:"");$("taskScenario").innerHTML=available.map(s=>`<option value="${s.id}" ${s.id===choice?"selected":""}>${escapeHtml(s.name)}</option>`).join("")}
function openNew(){scenarioOptions();$("taskForm").reset();$("editingId").value="";$("dialogEyebrow").textContent="NOUVEAU RÔLE";$("dialogTitle").innerHTML="Qu’est-ce qui mérite<br>votre attention ?";$("saveTask").textContent="Entrer en scène →";$("deleteTask").classList.remove("visible");$("taskDialog").showModal()}
function openEdit(id){const t=tasks.find(x=>x.id===id);scenarioOptions(t.scenario);$("editingId").value=id;$("taskTitle").value=t.title;$("taskRole").value=t.role;$("taskNature").value=t.nature;$("taskDuration").value=t.duration||"";$("taskDue").value=t.due||"";$("taskPositive").value=t.positive||"";$("taskNegative").value=t.negative||"";$("dialogEyebrow").textContent="RÉÉCRIRE LE RÔLE";$("dialogTitle").innerHTML="Ajuster la<br>distribution";$("saveTask").textContent="Enregistrer →";$("deleteTask").classList.add("visible");$("taskDialog").showModal()}
function openReview(){reviewQueue=tasks.filter(t=>t.environment===currentEnvironment&&dueForReview(t));reviewIndex=0;if(reviewQueue.length){renderReview();$("reviewDialog").showModal()}}
function renderReview(){const t=reviewQueue[reviewIndex];if(!t){$("reviewDialog").close();render();showToast("La distribution est clarifiée.");return}$("reviewProgress").textContent=`${reviewIndex+1} sur ${reviewQueue.length} · ${natureNames[t.nature]}`;$("reviewTaskTitle").textContent=t.title;$("reviewConsequences").innerHTML=`<div class="consequence-item"><b>Si je la fais</b>${escapeHtml(t.positive||"À préciser")}</div><div class="consequence-item negative"><b>Si je ne la fais pas</b>${escapeHtml(t.negative||"À préciser")}</div>`;$("decisionDetail").innerHTML="";document.querySelectorAll("[data-decision]").forEach(b=>b.classList.remove("selected"))}
function recordDecision(type,extra={}){const t=reviewQueue[reviewIndex];decisions.push({type,nature:t.nature,environment:t.environment,date:new Date().toISOString(),taskId:t.id});Object.assign(t,{lastReviewed:today(),...extra});reviewIndex++;renderReview()}
function chooseDecision(type,button){document.querySelectorAll("[data-decision]").forEach(b=>b.classList.remove("selected"));button.classList.add("selected");const detail=$("decisionDetail");if(type==="today")return recordDecision(type,{due:today()});if(type==="abandon")return recordDecision(type,{done:true,outcome:"abandon"});if(type==="delegate")return recordDecision(type,{done:true,outcome:"delegate"});if(type==="reschedule")detail.innerHTML=`<div class="detail-form"><input type="date" id="newDue" min="${today()}"><button onclick="confirmReschedule()">Fixer cette date</button></div>`;if(type==="split")detail.innerHTML=`<div class="detail-form"><input id="firstStep" placeholder="La plus petite première étape"><button onclick="confirmSplit()">Créer l’étape</button></div>`}
function confirmReschedule(){const due=$("newDue").value;if(!due)return;recordDecision("reschedule",{due})}
function confirmSplit(){const title=$("firstStep").value.trim();if(!title)return;const parent=reviewQueue[reviewIndex];tasks.push({id:Date.now(),title,role:"supporting",nature:parent.nature,duration:"",done:false,due:today(),positive:parent.positive,negative:parent.negative,order:tasks.length,lastReviewed:today(),outcome:"",scenario:parent.scenario,environment:parent.environment,week:weekKey(),dailyRank:0});recordDecision("split",{done:true,outcome:"split"})}
function renderStats(){const types=["today","reschedule","split","abandon","delegate"],total=types.reduce((n,k)=>n+decisions.filter(d=>d.type===k).length,0),completed=decisions.filter(d=>d.type==="completed").length;$("statsSummary").innerHTML=`<div class="stat-card"><b>${completed}</b><span>Tâches terminées</span></div><div class="stat-card"><b>${total}</b><span>Choix observés</span></div><div class="stat-card"><b>${decisions.length?Math.round(completed/decisions.length*100):0}%</b><span>Sorties terminées</span></div>`;$("statsBars").innerHTML=types.map(type=>{const n=decisions.filter(d=>d.type===type).length,p=total?Math.round(n/total*100):0;return `<div class="bar-row"><span>${decisionNames[type]}</span><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><b>${n}</b></div>`}).join("");const top=types.map(type=>[type,decisions.filter(d=>d.type===type).length]).sort((a,b)=>b[1]-a[1])[0];$("statsNote").textContent=total?`Pour l’instant, ton réflexe le plus fréquent est « ${decisionNames[top[0]].toLowerCase()} ». Ce n’est pas un verdict : simplement une tendance à observer.`:"Tes tendances apparaîtront ici après quelques revues. L’objectif n’est pas la performance, mais la compréhension."}
function scenarioName(id){const scenario=scenarios.find(s=>s.id===id);return scenario?scenario.name:"Général"}
function scenarioProgress(id){const list=tasks.filter(t=>t.week===weekKey()&&t.scenario===id),done=list.filter(t=>t.done).length;return {done,total:list.length,percent:list.length?Math.round(done/list.length*100):0}}
function renderMobile(){
  $("mobileApp").classList.toggle("environment-personal",currentEnvironment==="personal");document.querySelectorAll("[data-environment]").forEach(b=>b.classList.toggle("active",b.dataset.environment===currentEnvironment));
  $("mobileDate").textContent=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
  const priorities=tasks.filter(t=>!t.done&&t.environment===currentEnvironment&&t.dailyRank>0).sort((a,b)=>a.dailyRank-b.dailyRank).slice(0,3);
  $("priorityStack").innerHTML=[0,1,2].map(i=>{const t=priorities[i];return t?`<article class="priority-card"><span class="priority-number">TÊTE D’AFFICHE 0${i+1} · ${escapeHtml(scenarioName(t.scenario))}</span><button class="priority-check" onclick="completeTask(${t.id})">✓</button><h2>${escapeHtml(t.title)}</h2>${natureBadge(t)}<button class="priority-edit" onclick="openEdit(${t.id})">•••</button></article>`:`<div class="empty-priority">Tête d’affiche ${i+1} encore libre — choisis-la dans Semaine.</div>`}).join("");
  const reviewable=tasks.filter(t=>t.environment===currentEnvironment&&dueForReview(t));$("mobileReviewCount").textContent=reviewable.length;$("mobileReview").disabled=reviewable.length===0;
  const environmentScenarios=scenarios.filter(s=>s.environment===currentEnvironment);$("scenarioFilters").innerHTML=`<button class="${scenarioFilter==="all"?"active":""}" onclick="setScenarioFilter('all')">Tous</button>`+environmentScenarios.map(s=>`<button class="${scenarioFilter===s.id?"active":""}" onclick="setScenarioFilter('${s.id}')">${escapeHtml(s.name)}</button>`).join("");
  const weekly=tasks.filter(t=>t.environment===currentEnvironment&&(scenarioViewAll?scenarioFilter!=="all"&&t.scenario===scenarioFilter:t.week===weekKey()&&!t.done&&(scenarioFilter==="all"||t.scenario===scenarioFilter))).sort((a,b)=>scenarioViewAll?b.week.localeCompare(a.week)||Number(a.done)-Number(b.done)||a.order-b.order:Number(a.done)-Number(b.done)||a.order-b.order);
  $("weekKicker").textContent=scenarioViewAll?`SCÉNARIO · ${scenarioName(scenarioFilter)}`:episodeInfo().label.toUpperCase();
  const taskCard=t=>`<article class="mobile-task ${t.done?"task-completed":""}"><button class="check" onclick="${t.done?`restoreTask(${t.id})`:`completeTask(${t.id})`}">${t.done?"✓":""}</button><div onclick="openEdit(${t.id})"><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(scenarioName(t.scenario))} · ${natureNames[t.nature]}${t.due?` · ${formatDue(t.due)}`:""}</p></div>${t.done?`<span class="completed-label">Terminé</span>`:`<button class="priority-toggle ${t.dailyRank?"selected":""}" onclick="togglePriority(${t.id})" aria-label="${t.dailyRank?"Retirer des têtes d’affiche":"Mettre en tête d’affiche"}">${spotlightIcon()}</button>`}</article>`;
  if(!weekly.length)$("mobileWeekList").innerHTML=`<p class="empty-priority">Aucune tâche dans cette sélection.</p>`;else if(scenarioViewAll){const groups=weekly.reduce((all,t)=>{if(!all[t.week])all[t.week]=[];all[t.week].push(t);return all},{});$("mobileWeekList").innerHTML=Object.entries(groups).map(([week,list])=>{const info=episodeInfo(week),done=list.filter(t=>t.done).length,percent=list.length?Math.round(done/list.length*100):0;return `<section class="episode-block"><div class="episode-heading"><div><span>SAISON ${info.season}</span><b>Épisode · Semaine ${info.week}</b></div><strong>${percent}%</strong></div>${list.map(taskCard).join("")}</section>`}).join("")}else $("mobileWeekList").innerHTML=weekly.map(taskCard).join("");
  renderMobileStats();
}
function renderMobileStats(){const choices=decisions.filter(d=>(d.environment||"pro")===currentEnvironment&&["today","reschedule","split","abandon","delegate"].includes(d.type)),completed=decisions.filter(d=>(d.environment||"pro")===currentEnvironment&&d.type==="completed").length;$("mobileStats").innerHTML=`<div class="mobile-stat-cards"><div class="mobile-stat"><b>${completed}</b><span>Tâches terminées</span></div><div class="mobile-stat"><b>${choices.length}</b><span>Choix observés</span></div></div>`+scenarios.filter(s=>s.environment===currentEnvironment).map(s=>{const p=scenarioProgress(s.id);return `<div class="scenario-progress"><div class="scenario-progress-head"><span>${escapeHtml(s.name)}</span><b>${p.percent}%</b></div><div class="scenario-track"><div class="scenario-fill" style="width:${p.percent}%"></div></div><small>${p.done} sur ${p.total} cette semaine</small></div>`}).join("")+`<div class="stats-bars">${["today","reschedule","split","abandon","delegate"].map(type=>{const n=choices.filter(d=>d.type===type).length,p=choices.length?Math.round(n/choices.length*100):0;return `<div class="bar-row"><span>${decisionNames[type]}</span><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><b>${n}</b></div>`}).join("")}</div>`}
function togglePriority(id){const t=tasks.find(x=>x.id===id);if(t.dailyRank){t.dailyRank=0}else{const used=tasks.filter(x=>!x.done&&x.environment===currentEnvironment&&x.dailyRank>0);if(used.length>=3){showToast("Trois têtes d’affiche sont déjà choisies.");return}t.dailyRank=used.length+1}normalizePriorities();render()}
function normalizePriorities(){["pro","personal"].forEach(env=>tasks.filter(t=>!t.done&&t.environment===env&&t.dailyRank>0).sort((a,b)=>a.dailyRank-b.dailyRank).forEach((t,i)=>t.dailyRank=i+1))}
function setScenarioFilter(id){scenarioFilter=id;scenarioViewAll=false;renderMobile()}
function openScenario(id){scenarioFilter=id;scenarioViewAll=true;$("scenarioDialog").close();document.querySelectorAll(".mobile-page").forEach(p=>p.classList.toggle("active",p.id==="weekPage"));document.querySelectorAll("[data-page]").forEach(n=>n.classList.toggle("active",n.dataset.page==="weekPage"));renderMobile()}
function openScenarios(){$("scenarioList").innerHTML=scenarios.filter(s=>s.environment===currentEnvironment).map(s=>{const p=scenarioProgress(s.id),episode=episodeInfo();return `<button class="scenario-row scenario-link" onclick="openScenario('${s.id}')"><div class="scenario-row-head"><div><b>${escapeHtml(s.name)}</b><small>${episode.label}</small></div><span>${p.percent}% · ${p.done}/${p.total} ›</span></div><div class="scenario-track"><div class="scenario-fill" style="width:${p.percent}%"></div></div></button>`}).join("");$("scenarioDialog").showModal()}
function switchEnvironment(env){currentEnvironment=env;scenarioFilter="all";scenarioViewAll=false;render()}
function exportData(){const backup={app:"Pro Cast",version:4,exportedAt:new Date().toISOString(),tasks,decisions,scenarios};const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`pro-cast-sauvegarde-${today()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast("Sauvegarde préparée.")}
async function importData(file){try{const backup=JSON.parse(await file.text());if(backup.app!=="Pro Cast"||!Array.isArray(backup.tasks)||!Array.isArray(backup.scenarios))throw new Error("format");if(!confirm(`Restaurer ${backup.tasks.length} tâches ? Les données actuelles seront remplacées.`))return;localStorage.setItem("procast-before-import",JSON.stringify({tasks,decisions,scenarios,date:new Date().toISOString()}));tasks=backup.tasks;decisions=Array.isArray(backup.decisions)?backup.decisions:[];scenarios=backup.scenarios;scenarioFilter="all";scenarioViewAll=false;save();$("scenarioDialog").close();render();showToast("Sauvegarde restaurée.")}catch(error){showToast("Ce fichier n’est pas une sauvegarde Pro Cast.")}finally{$("importFile").value=""}}
$("dateLabel").textContent=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());$("addTrigger").onclick=openNew;$("mobileAdd").onclick=openNew;$("cancelTask").onclick=closeTaskDialog;$("doneToggle").onclick=()=>$("doneList").classList.toggle("open");$("reviewTrigger").onclick=openReview;$("mobileReview").onclick=openReview;$("closeReview").onclick=()=>$("reviewDialog").close();$("statsTrigger").onclick=()=>{renderStats();$("statsDialog").showModal()};$("closeStats").onclick=()=>$("statsDialog").close();$("scenarioTrigger").onclick=openScenarios;$("closeScenarios").onclick=()=>$("scenarioDialog").close();document.querySelectorAll("[data-decision]").forEach(b=>b.onclick=()=>chooseDecision(b.dataset.decision,b));document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mobile-page").forEach(p=>p.classList.toggle("active",p.id===b.dataset.page));document.querySelectorAll("[data-page]").forEach(n=>n.classList.toggle("active",n===b));if(b.dataset.page==="observePage")renderMobileStats()});
$("scenarioForm").addEventListener("submit",e=>{e.preventDefault();const name=$("scenarioName").value.trim();if(!name)return;scenarios.push({id:`scenario-${Date.now()}`,name,environment:currentEnvironment});$("scenarioName").value="";openScenarios();render();showToast("Nouveau scénario en préparation.")});
document.querySelectorAll("[data-environment]").forEach(b=>b.onclick=()=>switchEnvironment(b.dataset.environment));
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"})));
$("exportData").onclick=exportData;$("importData").onclick=()=>$("importFile").click();$("importFile").onchange=e=>{if(e.target.files[0])importData(e.target.files[0])};
$("taskForm").addEventListener("submit",e=>{e.preventDefault();const title=$("taskTitle").value.trim();if(!title)return;const role=$("taskRole").value,id=Number($("editingId").value),due=$("taskDue").value;if(role==="headliner")tasks.forEach(t=>{if(t.role==="headliner"&&!t.done&&t.id!==id)t.role="supporting"});const values={title,role,nature:$("taskNature").value,scenario:$("taskScenario").value,environment:currentEnvironment,duration:$("taskDuration").value.trim(),due,week:weekKey(due),positive:$("taskPositive").value.trim(),negative:$("taskNegative").value.trim(),lastReviewed:""};if(id)Object.assign(tasks.find(t=>t.id===id),values);else tasks.push({id:Date.now(),...values,done:false,order:tasks.length,outcome:"",dailyRank:0});closeTaskDialog();render();showToast(id?"Le rôle a été réécrit.":"Le rôle est distribué.")});$("deleteTask").onclick=()=>{const id=Number($("editingId").value);tasks=tasks.filter(t=>t.id!==id);normalizePriorities();closeTaskDialog();render();showToast("Coupée au montage.")};$("resetDay").onclick=()=>{tasks=structuredClone(defaults).map((t,i)=>({...t,scenario:"general",environment:"pro",week:weekKey(),dailyRank:i<3?i+1:0}));decisions=[];render();showToast("La scène est prête.")};render();
